// Copy for the public /about page. JA mirrors the portfolio's i18n tone.
// `built` alternates plain / bold segments (even index plain, odd bold).

export type Language = 'en' | 'ja';

const en = {
  toggle: { label: 'EN', aria: 'EN, switch to Japanese' },
  hero: {
    badge: 'Personal project · 単語帳 = “vocabulary notebook”',
    titleBefore: 'Capture Japanese words the moment you hear them — and never ',
    titleHighlight: 'forget',
    titleAfter: ' them.',
    body: 'A single-user app I built to learn Japanese while living in Japan: fast AI-assisted capture, the memory of where each word came from, new words every morning from AI friends, and spaced-repetition review.',
    signIn: 'Sign in',
    portfolio: 'Portfolio ↗',
    private: 'It’s a private, single-account app (email allowlist) — this page is the tour.',
    mockupAlts: ['Capture screen', 'Practice flashcard', 'Browse list'],
  },
  features: [
    { title: 'Capture', jp: '取り込む', body: 'Type a word; Jisho + Gemini auto-fill the reading, Indonesian & English meanings, and an example. Tag where you heard it.' },
    { title: 'Browse', jp: '一覧', body: 'Every word as a table or bento grid, with furigana. Filter by source, mastery, or what’s due. Tap for full detail.' },
    { title: 'Practice', jp: '復習', body: 'SM-2 spaced-repetition flashcards. Flip, rate forgot / hard / easy, and the app schedules the next review.' },
    { title: 'Speak', jp: '話す', body: 'See the meaning, say the word out loud. Speech recognition checks what it heard against the word, then plays the correct pronunciation so you can compare.' },
    { title: 'Friends', jp: '友達', body: 'Create AI characters — a casual friend, a polite coworker — with their own themes. Each day they mention 4 new words in a one-line message; keep the ones worth learning.' },
    { title: 'Reminders', jp: '通知', body: 'A push notification at 07:00 brings a friend’s line and what’s due today, so new words keep coming even on days I forget to open the app.' },
  ],
  story: {
    heading: 'Why I built it',
    alts: [
      'Handwritten notebook page: Japanese words with furigana, each followed by an arrow and an English meaning',
      'Handwritten notebook page: Japanese words with furigana and mixed English / Indonesian meanings',
    ],
    body: [
      'This is how I used to learn: every new word from anime, manga, or daily life in Japan went into a paper notebook — kanji, furigana on top, an arrow, then whatever meaning came to mind, half English, half Indonesian.',
      'It didn’t hold up. Every reading took a lookup, I forgot where I’d heard each word, and the pages never quizzed me — so I rarely flipped back.',
      'tangocho keeps the notebook habit and does the slow parts: it fills in the reading and meanings, remembers the source, and tells me which words to review today.',
    ],
    sample: {
      label: 'The same word in tangocho',
      source: 'Anime',
      en: 'foreshadowing',
      id: 'petunjuk awal; memberi tanda',
      example: '最初[さいしょ]の場面[ばめん]は結末[けつまつ]への伏線[ふくせん]だった。',
    },
  },
  seeIt: 'See it in action',
  shots: {
    capture: { alt: 'Capture screen auto-filling a word', caption: 'Capture · AI auto-fill' },
    browse: { alt: 'Browse list with filters', caption: 'Browse · filter & search' },
    detail: { alt: 'Word detail with furigana example', caption: 'Detail · meaning, example, source' },
    practice: { alt: 'Practice flashcard', caption: 'Practice · SM-2 flashcards' },
    speak: { alt: 'Speak mode: the meaning is shown and a mic button asks for the word in Japanese', caption: 'Speak · say it out loud' },
    progress: { alt: 'Progress dashboard with mastery, daily reviews and friend-word save rate', caption: 'Progress · mastery & save rate' },
    friends: { alt: 'Friends page with a casual friend and a polite coworker, and the daily notification toggle', caption: 'Friends · AI characters' },
    home: { alt: 'Home with today’s words from friends', caption: 'Home · today’s words' },
  },
  carousel: {
    prev: 'Previous screen',
    next: 'Next screen',
    goTo: (n: number) => `Go to screen ${n}`,
  },
  changelog: {
    heading: 'What’s new',
    jp: '更新履歴',
    seeAll: 'See all updates →',
    readPost: 'Read the story ↗',
    pageTitle: 'Updates',
    pageIntro: 'Every feature added to tangocho, newest first.',
    back: '← Back to the tour',
  },
  builtHeading: 'How it’s built',
  built: [
    'A full-stack PWA on entirely free tiers. Words are auto-enriched by a ',
    'Jisho → Gemini fallback',
    ' pipeline, review scheduling uses a hand-implemented ',
    'SM-2',
    ' algorithm, Speak mode runs entirely in the browser on the ',
    'Web Speech API',
    ' (recognition + Japanese text-to-speech, no audio stored). Daily friend words come from one ',
    'Gemini call a day',
    ', checked against Jisho and deduplicated, and a ',
    'Vercel cron + Web Push',
    ' delivers them at 07:00. Every row is protected by Postgres ',
    'row-level security',
    ' with a single-user Google OAuth allowlist.',
  ],
  footerBefore: 'Built by ',
  footerAfter: '.',
};

export type AboutCopy = typeof en;

const ja: AboutCopy = {
  toggle: { label: 'JP', aria: 'JP, switch to English' },
  hero: {
    badge: '個人プロジェクト · tangocho = 単語帳',
    titleBefore: '聞いたその瞬間に、日本語の単語を取り込む。もう',
    titleHighlight: '忘れない',
    titleAfter: '。',
    body: '日本で暮らしながら日本語を学ぶために作った、自分専用のアプリ。AIでサッと単語を取り込み、どこで覚えたかを記録し、毎朝AIの友達から新しい単語が届き、間隔反復で復習する。',
    signIn: 'ログイン',
    portfolio: 'ポートフォリオ ↗',
    private: '許可された1アカウントだけが使える非公開アプリ（メール許可リスト）。このページはその紹介です。',
    mockupAlts: ['取り込み画面', '復習フラッシュカード', '単語一覧'],
  },
  features: [
    { title: 'Capture', jp: '取り込む', body: '単語を入力するだけで、Jisho + Geminiが読み・インドネシア語と英語の意味・例文を自動入力。どこで聞いたかもタグ付けできる。' },
    { title: 'Browse', jp: '一覧', body: '全単語をテーブルかベントーグリッドで、ふりがな付きで表示。出典・習熟度・復習期限で絞り込み、タップで詳細を確認。' },
    { title: 'Practice', jp: '復習', body: 'SM-2の間隔反復フラッシュカード。めくって「忘れた／難しい／簡単」で評価すると、次の復習日が自動で決まる。' },
    { title: 'Speak', jp: '話す', body: '意味を見て、単語を声に出して言う。音声認識が聞き取った内容を答えと照合し、正しい発音を再生して聞き比べられる。' },
    { title: 'Friends', jp: '友達', body: 'タメ口の友達や敬語の同僚など、テーマを持ったAIキャラクターを作れる。毎日ひとことメッセージで新しい単語を4つ教えてくれて、覚えたいものだけ保存する。' },
    { title: 'Reminders', jp: '通知', body: '毎朝7時に、友達のひとことと今日の復習数をプッシュ通知でお知らせ。アプリを開き忘れた日も、新しい単語が届く。' },
  ],
  story: {
    heading: '作ったきっかけ',
    alts: [
      '手書きのノート：ふりがな付きの日本語の単語と、矢印の先に英語の意味',
      '手書きのノート：ふりがな付きの日本語の単語と、英語・インドネシア語が混ざった意味',
    ],
    body: [
      '以前はこうやって覚えていた。アニメや漫画、日本での生活で出会った新しい単語を、紙のノートに書く。漢字、上にふりがな、矢印、そして思いついた意味を英語とインドネシア語で。',
      'でも続かなかった。読みを毎回調べるのは手間で、どこで聞いた単語かも忘れ、ノートはテストしてくれない。だから見返すこともほとんどなかった。',
      'tangochoはノートの習慣はそのままに、面倒な部分を代わりにやってくれる。読みと意味を自動で入力し、出典を記録し、今日復習すべき単語を教えてくれる。',
    ],
    sample: {
      label: 'tangochoでは同じ単語がこうなる',
      source: 'アニメ',
      en: 'foreshadowing',
      id: 'petunjuk awal; memberi tanda',
      example: '最初[さいしょ]の場面[ばめん]は結末[けつまつ]への伏線[ふくせん]だった。',
    },
  },
  seeIt: '実際の画面',
  shots: {
    capture: { alt: '単語を自動入力している取り込み画面', caption: 'Capture · AIで自動入力' },
    browse: { alt: 'フィルター付きの単語一覧', caption: 'Browse · 絞り込み・検索' },
    detail: { alt: 'ふりがな付き例文のある単語詳細', caption: 'Detail · 意味・例文・出典' },
    practice: { alt: '復習フラッシュカード', caption: 'Practice · SM-2フラッシュカード' },
    speak: { alt: 'Speakモード：意味が表示され、マイクボタンで日本語の単語を言う画面', caption: 'Speak · 声に出して言う' },
    progress: { alt: '習熟度、毎日の復習数、友達の単語の保存率がある進捗ダッシュボード', caption: 'Progress · 習熟度と保存率' },
    friends: { alt: 'タメ口の友達と敬語の同僚、毎日の通知設定がある友達ページ', caption: 'Friends · AIキャラクター' },
    home: { alt: '友達からの今日の単語があるホーム', caption: 'Home · 今日の単語' },
  },
  carousel: {
    prev: '前の画面',
    next: '次の画面',
    goTo: (n: number) => `画面${n}へ`,
  },
  changelog: {
    heading: 'What’s new',
    jp: '更新履歴',
    seeAll: 'すべての更新を見る →',
    readPost: '記事を読む ↗',
    pageTitle: '更新履歴',
    pageIntro: 'tangochoに追加した機能の一覧（新しい順）。',
    back: '← 紹介ページに戻る',
  },
  builtHeading: '技術構成',
  built: [
    'すべて無料枠で動くフルスタックPWA。単語は',
    'Jisho → Geminiフォールバック',
    'のパイプラインで自動補完し、復習スケジュールは自前で実装した',
    'SM-2',
    'アルゴリズムで管理。Speakモードは',
    'Web Speech API',
    'を使ってブラウザ内だけで完結（音声認識＋日本語読み上げ、音声は保存しない）。友達の単語は',
    '1日1回のGemini呼び出し',
    'で作り、Jishoで確認して重複を除き、',
    'Vercel Cron＋Web Push',
    'で毎朝7時に届ける。全テーブルをPostgresの',
    '行レベルセキュリティ',
    'で保護し、Google OAuthの許可リストで利用者を1人に限定。',
  ],
  footerBefore: '制作：',
  footerAfter: '',
};

export const aboutCopy: Record<Language, AboutCopy> = { en, ja };
